const $=id=>document.getElementById(id);
const nowISO=()=>new Date().toISOString();
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const shortDate=v=>v?new Date(v).toLocaleDateString('en-AU',{day:'numeric',month:'short',year:'numeric'}):'—';
function randomToken(){const a=new Uint8Array(18);crypto.getRandomValues(a);return Array.from(a,b=>b.toString(16).padStart(2,'0')).join('')}
const Storage={key:'proposal_studio_v6',load(){try{return JSON.parse(localStorage.getItem(this.key))||null}catch{return null}},save(x){localStorage.setItem(this.key,JSON.stringify(x))}};
const defaults={dealership:'Knox Ford',consultant:'Joel Hill',title:'New Vehicle Sales',phone:'',email:'',validity:7,disclaimer:'Pricing and vehicle availability remain subject to final contract, stock availability and manufacturer changes.',privacy:'This proposal is intended only for the customer named.',finance:'Indicative finance illustration only. Subject to lender approval and lending criteria.'};
function demoData(){return {customerName:'Demo Customer',customerEmail:'',quoteNo:'DEMO-001',quoteDate:'',make:'Ford',modelCode:'',vehicle:'Demo Ford Vehicle',bodyType:'',stockNo:'',colour:'',engine:'',transmission:'',salePrice:70000,dealerDelivery:2000,salePriceIncAccOpt:72000,discount:1000,subtotalSalePrice:71000,registration:350,plateFee:250,adminFee:100,ctp:600,lct:0,stampDuty:3000,insurance:0,driveaway:75300,tradeValue:0,tradePayout:0,deposit:0,changeover:75300,accessoriesPrice:0,accessories:'',personalMessage:'Thanks for the opportunity to prepare this vehicle proposal for you.',features:'Vehicle highlights | Tailored to the selected vehicle\nTechnology | Connected features and driver convenience\nOwnership | Supported by Knox Ford',vehicleImage:''}}
function seed(){const t=nowISO(),d=demoData();return {id:'demo',token:randomToken(),status:'Published',linkEnabled:true,expiry:'',pin:'',createdAt:t,updatedAt:t,viewCount:0,firstViewed:'',lastViewed:'',pricingViewed:false,reachedBottom:false,customerResponse:'',draft:null,published:{...d,version:1,publishedAt:t},versions:[{version:1,publishedAt:t,user:'Joel Hill',note:'Demo proposal',data:d}],events:[{type:'published',at:t,text:'Demo proposal published'}],requests:[]}}
let db=Storage.load()||{settings:{...defaults},proposals:[seed()]};Storage.save(db);
let editingId=null,currentRaw=[],currentPdfUrl='',currentConfidence={},currentImage='';
function persist(){Storage.save(db)}
function settings(){return {...defaults,...db.settings}}
function getProposal(id){return db.proposals.find(p=>p.id===id)}
function addEvent(p,type,text){p.events=p.events||[];p.events.unshift({type,at:nowISO(),text});p.updatedAt=nowISO();persist()}
function defaultFeatures(v=''){return `Vehicle highlights | Key features for ${v||'the selected vehicle'}\nPracticality | Tailored to customer requirements\nTechnology | Connected features and driver convenience\nOwnership | Supported by Knox Ford`}
const fields=['customerName','customerEmail','quoteNo','quoteDate','make','modelCode','vehicle','bodyType','stockNo','colour','engine','transmission','salePrice','dealerDelivery','salePriceIncAccOpt','discount','subtotalSalePrice','registration','plateFee','adminFee','ctp','lct','stampDuty','insurance','driveaway','tradeValue','tradePayout','deposit','changeover','accessoriesPrice','accessories','personalMessage','features'];
function fillForm(d){fields.forEach(k=>{if($(k))$(k).value=d[k]??''});currentImage=d.vehicleImage||'';renderImageThumb();applyConfidence(d)}
function readForm(){const d={};fields.forEach(k=>{if($(k))d[k]=$(k).value});d.vehicleImage=currentImage;return d}
function num(s){return Number(String(s||'').replace(/[^0-9.-]/g,''))||0}
function showPanel(name){['dashboard','wizard','settings','parserTest'].forEach(x=>$(x).classList.toggle('hidden',x!==name));document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));if(name==='dashboard')$('navDash').classList.add('active');if(name==='wizard')$('navCreate').classList.add('active');if(name==='settings')$('navSettings').classList.add('active');if(name==='parserTest')$('navParser').classList.add('active')}
function setStep(n){[1,2,3,4].forEach(i=>{$('step'+i)?.classList.toggle('hidden',i!==n);document.querySelector(`[data-step="${i}"]`)?.classList.toggle('active',i===n)});if(n===3)$('proposalPreview').innerHTML=proposalHTML(readForm(),{draft:true})}
function toast(t){$('toast').textContent=t;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2000)}
function renderRows(){const ps=[...db.proposals].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('proposalRows').innerHTML=ps.map(p=>{const d=p.published||p.draft||{};const eng=p.viewCount?`${p.viewCount} view${p.viewCount===1?'':'s'}${p.pricingViewed?' · Pricing viewed':''}`:'Not viewed';return `<tr><td><strong>${esc(d.customerName||'Untitled')}</strong><div class="muted">${esc(d.quoteNo||'')}</div></td><td>${esc(d.vehicle||'—')}</td><td><strong>${money(d.driveaway||0)}</strong></td><td><span class="badge">${esc(p.status)}</span></td><td>${eng}</td><td>${shortDate(p.updatedAt)}</td><td><div class="actions-inline"><button class="btn ghost small" data-edit="${p.id}">Edit</button><button class="btn ghost small" data-open="${p.id}">View</button><button class="btn ghost small" data-copy="${p.id}">Copy Link</button><button class="btn ghost small" data-history="${p.id}">Activity</button></div></td></tr>`}).join('');document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProposal(b.dataset.edit));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openCustomerById(b.dataset.open));document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyProposalLink(b.dataset.copy));document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>showActivity(b.dataset.history));$('sTotal').textContent=ps.length;$('sPublished').textContent=ps.filter(p=>p.published).length;$('sViewed').textContent=ps.filter(p=>p.viewCount>0).length;$('sResponded').textContent=ps.filter(p=>p.customerResponse||p.requests?.length).length}
function createFlow(){editingId=null;currentRaw=[];currentPdfUrl='';currentImage='';currentConfidence={};showPanel('wizard');setStep(1)}
function editProposal(id){const p=getProposal(id);if(!p)return;editingId=id;fillForm(p.draft||p.published||{});$('expiry').value=p.expiry||'';$('pin').value=p.pin||'';$('linkEnabled').value=String(p.linkEnabled!==false);currentRaw=p.rawLines||[];showPanel('wizard');setStep(2);toast('Editing draft — live proposal unchanged until publish')}
function saveDraftFromForm(){let p=editingId?getProposal(editingId):null;if(!p){p={id:'p_'+randomToken().slice(0,12),token:randomToken(),status:'Draft',linkEnabled:true,expiry:'',pin:'',createdAt:nowISO(),updatedAt:nowISO(),viewCount:0,pricingViewed:false,reachedBottom:false,customerResponse:'',published:null,versions:[],events:[],requests:[]};db.proposals.unshift(p);editingId=p.id}const d=readForm();p.draft={...d,features:d.features||defaultFeatures(d.vehicle)};p.rawLines=[...currentRaw];p.updatedAt=nowISO();if(!p.published)p.status='Draft';addEvent(p,'draft','Draft saved');renderRows();toast('Draft saved');return p}
function publishCurrent(){const p=saveDraftFromForm();p.expiry=$('expiry').value||'';p.pin=$('pin').value.trim();p.linkEnabled=$('linkEnabled').value==='true';const version=(p.versions?.length||0)+1;const data=JSON.parse(JSON.stringify(p.draft));p.published={...data,version,publishedAt:nowISO()};p.versions.unshift({version,publishedAt:nowISO(),user:settings().consultant,note:$('versionNote').value.trim()||`Version ${version}`,data});p.draft=null;p.status='Published';addEvent(p,'published',`Version ${version} published`);renderRows();showPanel('dashboard');toast('Proposal published')}
function proposalLink(p){return location.href.split('#')[0]+'#proposal='+p.token}
async function copyProposalLink(id){const p=getProposal(id);if(!p)return;await navigator.clipboard.writeText(proposalLink(p));toast('Customer link copied')}
function parseAccessories(text){return String(text||'').split(/\n/).map(s=>s.trim()).filter(Boolean).map(line=>{const [name,...rest]=line.split('|');return{name:name.trim(),price:num(rest.join('|'))}})}
function parseFeatures(text){return String(text||'').split(/\n/).map(s=>s.trim()).filter(Boolean).map(line=>{const [title,...rest]=line.split('|');return{title:title.trim(),desc:rest.join('|').trim()||'Included in the selected vehicle specification.'}})}
